ALTER TABLE grade MODIFY course VARCHAR(20) NOT NULL;
ALTER TABLE grade MODIFY Num INT(10) NOT NULL AFTER id;
ALTER TABLE grade CHANGE Grade score VARCHAR(4);
ALTER TABLE grade DROP FOREIGN KEY grade_ibfk_1;
ALTER TABLE grade ENGINE=MYISAM;
ALTER TABLE student DROP address;
ALTER TABLE student ADD phone VARCHAR(15);
RENAME TABLE grade TO gradeinfo;
DROP TABLE student;